// Generated by https://quicktype.io

export interface Post {
    id: string;
    text: string;
    image: string;
    date: number;
    author: string;
    like: Array<string>;
    authorImage: string;
}

